# Generated by Django 6.0.4 on 2026-05-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_taskmodel_status_profilemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='status',
            field=models.CharField(choices=[('InProgress', 'InProgress'), ('pending', 'pending'), ('Canceled', 'Canceled'), ('Completed', 'Completed')], max_length=20, null=True),
        ),
    ]
