# Generated by Django 6.0.4 on 2026-05-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_taskmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Canceled', 'Canceled'), ('pending', 'pending'), ('InProgress', 'InProgress')], max_length=20, null=True),
        ),
    ]
