# Generated by Django 6.0.4 on 2026-05-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_taskmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('Completed', 'Completed'), ('InProgress', 'InProgress'), ('Canceled', 'Canceled')], max_length=20, null=True),
        ),
    ]
