# Generated by Django 6.0.4 on 2026-05-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_taskmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='status',
            field=models.CharField(choices=[('InProgress', 'InProgress'), ('Completed', 'Completed'), ('pending', 'pending'), ('Canceled', 'Canceled')], max_length=20, null=True),
        ),
    ]
